// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwpKwao0OYhWQ3qdrBhaWxK7SVH0IpKVY',
    appId: '1:843062927229:android:dc227f366f9e3ffa70f614',
    messagingSenderId: '843062927229',
    projectId: 'itienda-585d8',
    storageBucket: 'itienda-585d8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAx6ktEJYeIxzKgu-a4ucdFknHpCZDpBkc',
    appId: '1:843062927229:ios:4729b5a4a8a6971c70f614',
    messagingSenderId: '843062927229',
    projectId: 'itienda-585d8',
    storageBucket: 'itienda-585d8.appspot.com',
    androidClientId: '843062927229-ksl0n62v7q94c0n23mpndmonkq9ogor8.apps.googleusercontent.com',
    iosClientId: '843062927229-cl37fuc818mu1hjhdeb2du73g0ulabjk.apps.googleusercontent.com',
    iosBundleId: 'com.example.itienda',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnPB_nOCCC8yczv1Ct1CRvBN4zdrIc11s',
    appId: '1:843062927229:web:c361b8192fd568a770f614',
    messagingSenderId: '843062927229',
    projectId: 'itienda-585d8',
    authDomain: 'itienda-585d8.firebaseapp.com',
    storageBucket: 'itienda-585d8.appspot.com',
    measurementId: 'G-MP3Y72V1V1',
  );

}